# Generated by Django 5.2.7 on 2025-11-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicpostsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikesCount',
            field=models.IntegerField(default=0),
        ),
    ]
